version: '3'
services:
  my-service: 
    image: nodejsdocker
    ports:
        - 3500:3000
    environment:
        - MYSQL_HOST=172.17.0.1
        - MYSQL_USER=root
        - MYSQL_PASSWORD=""
        - MYSQL_DATABASE=zoo
        - MYSQL_PORT=3006